GITHUB_CONSUMER_KEY: 08ab9a3fd61d9e4e51b7
GITHUB_CONSUMER_SECRET: 91deb8f2d848f134ab6eb7c54c06971cc24f84ba
FACEBOOK_CONSUMER_KEY: 584761061537630
FACEBOOK_CONSUMER_SECRET: 9bf113994fe225d4566eb899fa10c730
TWITTER_CONSUMER_KEY: asqW069G4hJQrG6BqUONg
TWITTER_CONSUMER_SECRET: hyHuhFphxH7sBu1tWxtBzsmRHej97QTgxfoETPFS4Z8
GOOGLE_CONSUMER_KEY: 823690182699.apps.googleusercontent.com
GOOGLE_CONSUMER_SECRET: JUCkWbys54oDq_Wfe187ueDb
DOMAIN: "social-reviewing.com"
SENDGRID_USERNAME:
SENDGRID_PASSWORD:
DOTCLOUD_DB_MYSQL_HOST:
DOTCLOUD_DB_MYSQL_PORT:
DOTCLOUD_DB_MYSQL_LOGIN:
DOTCLOUD_DB_MYSQL_PASSWORD:
