development:
  adapter: mysql2
  encoding: utf8
  database: social_reviewing_development
  username: root

test:
  adapter: mysql2
  encoding: utf8
  database: social_reviewing_test
  username: root

production:
  adapter: mysql2
  encoding: utf8
  database: social_reviewing_production
  username: <%= SRConfig.dotcloud_db_mysql_login %>
  password: <%= SRConfig.dotcloud_db_mysql_password %>
  host: <%= SRConfig.dotcloud_db_mysql_host %>
  port: <%= SRConfig.dotcloud_db_mysql_port %>
