development:
  adapter: mysql2
  encoding: utf8
  database: comment_my_projects_development
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  database: comment_my_projects_test
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
