development:
  adapter: mysql2
  encoding: utf8
  database: comment_my_projects_development
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  database: comment_my_projects_test
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  database: comment_my_projects_production
  username: root
  password: root
