development:
  adapter: postgresql
  encoding: utf8
  database: comment_my_projects_development
  username: comment_my_projects
  password: comment_my_projects

test:
  adapter: postgresql
  encoding: utf8
  database: comment_my_projects_test
  username: comment_my_projects
  password: comment_my_projects

production:
  adapter: postgresql
  encoding: utf8
  database: comment_my_projects_production
  username: comment_my_projects
  password: comment_my_projects
