mysql: &mysql
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= SRConfig.db_login %>
  password: <%= SRConfig.db_password %>
  host: <%= SRConfig.db_host %>
  port: <%= SRConfig.db_port %>
  socket: <%= SRConfig.db_socket %>

development:
  <<: *mysql
  database: social_reviewing_development

test:
  <<: *mysql
  database: social_reviewing_test

production:
  <<: *mysql
  database: social_reviewing_production
