---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: staging
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn_nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-f4ec2e84
  image_type: m1.small
  image_id: ami-eafa5883
  security_groups:
  - social-reviewing_staging_default
  - social-reviewing_staging_web
  - social-reviewing_staging_web_tools
  - social-reviewing_staging_staging
  - social-reviewing_staging_app
  - social-reviewing_staging_unicorn_nginx
  - social-reviewing_staging_collectd
  - social-reviewing_staging_common
  - social-reviewing_staging_monit
  - social-reviewing_staging_db
  - social-reviewing_staging_mysql
  - social-reviewing_staging_mysql_master
  - social-reviewing_staging_examples
  - social-reviewing_staging_graphite_server
  - social-reviewing_staging_graphite_web
  - social-reviewing_staging_haproxy
  - social-reviewing_staging_nginx
  - social-reviewing_staging_unicorn
  external_host: ec2-50-16-79-222.compute-1.amazonaws.com
  external_ip: 50.16.79.222
  internal_host: ip-10-190-211-78.ec2.internal
  internal_ip: 10.190.211.78
  zone: us-east-1b
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
